version: 2.1

orbs:
  aws-cli: opensimsim/aws-cli@1.2.1

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:14.16.1-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run build --prod
      - run:
          name: Deploy to S3 bucket
          command: |
           aws configure set aws_access_key_id ${AKIA3FUG5DY4Z3LFJJOT}
            aws configure set aws_secret_access_key ${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}
            aws s3 cp dist/ s3://mlmknjnjnj
            

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
