version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - run: npm install
      - run: npm run build --prod
      - run:
          name: Deploy to S3 bucket
          command: |
           aws configure set aws_access_key_id ${AKIA3FUG5DY4Z3LFJJOT}
            aws configure set aws_secret_access_key ${gPVU1CCU39GBupnNhEx3s1QFQC5o5JN0FawrY8YI}
            aws s3 cp dist/ s3://mlmknjnjnj
            
workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
