version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - run: npm install
      - run: npm run build --prod
      - run:
          name: Deploy to S3 bucket
          command: |
           
            
workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
